dist: xenial
language: python

python:
  - "3.6"
  - "3.7"
  # No tf-nightly for this version
  # - "3.8"
  # Cython and/or Numpy fails with permission errors
  # - "pypy3"

install:
  - pip install -r requirements.txt

script:
  - pylint symbolic_pymc/ tests/
  - if [[ `command -v black` ]]; then
      black --check symbolic_pymc tests;
    fi
  - pytest -v tests/ --cov=symbolic_pymc/

after_success:
  - coveralls
