dist: xenial
language: python

matrix:
  include:
  - name: "Python 3.6 Lint"
    python: 3.6
    env: PYTHON_VERSION=3.6 NAME="LINT"
  - name: "Python 3.6 Unit Test"
    python: 3.6
    env: PYTHON_VERSION=3.6 NAME="UNIT"

install:
  - pip install -r requirements.txt
  - pip freeze

script:
  - if [[ $NAME == UNIT ]]; then pytest -v tests/ --cov=symbolic_pymc/; fi
  - if [[ $NAME == LINT ]]; then make lint; fi

after_success:
  - echo $(pwd)
  - ls -la
  - if [[ $NAME == UNIT ]]; then sed -i 's/\/opt\/symbolic-pymc/\/home\/travis\/build\/pymc-devs\/symbolic-pymc/g' .coverage; fi
  - if [[ $NAME == UNIT ]]; then coveralls; fi
